version: '3'
services:

  elasticsearch:
    container_name: "es"
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    volumes:
      - "./elasticsearch/data:/usr/share/elasticsearch/data"
    ports:
      - "9200:9200"

  kibana:
    container_name: "kibana"
    image: docker.elastic.co/kibana/kibana:6.4.0
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
